package com.hwl.vue.mapper;

import com.hwl.vue.been.User;
import com.hwl.vue.been.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table easyuser
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    int updateByPrimaryKey(User record);
}