package com.hwl.vue.been;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.id
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.username
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.password
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.email
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.role
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column easyuser.state
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.id
     *
     * @return the value of easyuser.id
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.id
     *
     * @param id the value for easyuser.id
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.username
     *
     * @return the value of easyuser.username
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.username
     *
     * @param username the value for easyuser.username
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.password
     *
     * @return the value of easyuser.password
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.password
     *
     * @param password the value for easyuser.password
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.email
     *
     * @return the value of easyuser.email
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.email
     *
     * @param email the value for easyuser.email
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.role
     *
     * @return the value of easyuser.role
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.role
     *
     * @param role the value for easyuser.role
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column easyuser.state
     *
     * @return the value of easyuser.state
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column easyuser.state
     *
     * @param state the value for easyuser.state
     *
     * @mbggenerated Mon Jul 20 15:26:31 CST 2020
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}